
package ua.nure.registryservice.serviceimplementation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ServiceRegistryImplService", targetNamespace = "http://ServiceImplementation.RegistryService.nure.ua/", wsdlLocation = "http://localhost:8089/ws/Registry?wsdl")
public class ServiceRegistryImplService
    extends Service
{

    private final static URL SERVICEREGISTRYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICEREGISTRYIMPLSERVICE_EXCEPTION;
    private final static QName SERVICEREGISTRYIMPLSERVICE_QNAME = new QName("http://ServiceImplementation.RegistryService.nure.ua/", "ServiceRegistryImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/ws/Registry?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICEREGISTRYIMPLSERVICE_WSDL_LOCATION = url;
        SERVICEREGISTRYIMPLSERVICE_EXCEPTION = e;
    }

    public ServiceRegistryImplService() {
        super(__getWsdlLocation(), SERVICEREGISTRYIMPLSERVICE_QNAME);
    }

    public ServiceRegistryImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICEREGISTRYIMPLSERVICE_QNAME, features);
    }

    public ServiceRegistryImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICEREGISTRYIMPLSERVICE_QNAME);
    }

    public ServiceRegistryImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICEREGISTRYIMPLSERVICE_QNAME, features);
    }

    public ServiceRegistryImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceRegistryImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServiceRegistry
     */
    @WebEndpoint(name = "ServiceRegistryImplPort")
    public ServiceRegistry getServiceRegistryImplPort() {
        return super.getPort(new QName("http://ServiceImplementation.RegistryService.nure.ua/", "ServiceRegistryImplPort"), ServiceRegistry.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceRegistry
     */
    @WebEndpoint(name = "ServiceRegistryImplPort")
    public ServiceRegistry getServiceRegistryImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ServiceImplementation.RegistryService.nure.ua/", "ServiceRegistryImplPort"), ServiceRegistry.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICEREGISTRYIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICEREGISTRYIMPLSERVICE_EXCEPTION;
        }
        return SERVICEREGISTRYIMPLSERVICE_WSDL_LOCATION;
    }

}
