
package ua.nure.registryservice.serviceimplementation;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ServiceRegistry", targetNamespace = "http://ServiceImplementation.RegistryService.nure.ua/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceRegistry {


    /**
     * 
     * @param arg0
     * @return
     *     returns ua.nure.registryservice.serviceimplementation.Registry
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerService", targetNamespace = "http://ServiceImplementation.RegistryService.nure.ua/", className = "ua.nure.registryservice.serviceimplementation.RegisterService")
    @ResponseWrapper(localName = "registerServiceResponse", targetNamespace = "http://ServiceImplementation.RegistryService.nure.ua/", className = "ua.nure.registryservice.serviceimplementation.RegisterServiceResponse")
    @Action(input = "http://ServiceImplementation.RegistryService.nure.ua/ServiceRegistry/registerServiceRequest", output = "http://ServiceImplementation.RegistryService.nure.ua/ServiceRegistry/registerServiceResponse")
    public Registry registerService(
        @WebParam(name = "arg0", targetNamespace = "")
        Registry arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "deleteService", targetNamespace = "http://ServiceImplementation.RegistryService.nure.ua/", className = "ua.nure.registryservice.serviceimplementation.DeleteService")
    @ResponseWrapper(localName = "deleteServiceResponse", targetNamespace = "http://ServiceImplementation.RegistryService.nure.ua/", className = "ua.nure.registryservice.serviceimplementation.DeleteServiceResponse")
    @Action(input = "http://ServiceImplementation.RegistryService.nure.ua/ServiceRegistry/deleteServiceRequest", output = "http://ServiceImplementation.RegistryService.nure.ua/ServiceRegistry/deleteServiceResponse")
    public void deleteService(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<ua.nure.registryservice.serviceimplementation.Registry>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllServices", targetNamespace = "http://ServiceImplementation.RegistryService.nure.ua/", className = "ua.nure.registryservice.serviceimplementation.GetAllServices")
    @ResponseWrapper(localName = "getAllServicesResponse", targetNamespace = "http://ServiceImplementation.RegistryService.nure.ua/", className = "ua.nure.registryservice.serviceimplementation.GetAllServicesResponse")
    @Action(input = "http://ServiceImplementation.RegistryService.nure.ua/ServiceRegistry/getAllServicesRequest", output = "http://ServiceImplementation.RegistryService.nure.ua/ServiceRegistry/getAllServicesResponse")
    public List<Registry> getAllServices();

    /**
     * 
     * @param arg0
     * @return
     *     returns ua.nure.registryservice.serviceimplementation.Registry
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServiceByName", targetNamespace = "http://ServiceImplementation.RegistryService.nure.ua/", className = "ua.nure.registryservice.serviceimplementation.GetServiceByName")
    @ResponseWrapper(localName = "getServiceByNameResponse", targetNamespace = "http://ServiceImplementation.RegistryService.nure.ua/", className = "ua.nure.registryservice.serviceimplementation.GetServiceByNameResponse")
    @Action(input = "http://ServiceImplementation.RegistryService.nure.ua/ServiceRegistry/getServiceByNameRequest", output = "http://ServiceImplementation.RegistryService.nure.ua/ServiceRegistry/getServiceByNameResponse")
    public Registry getServiceByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns ua.nure.registryservice.serviceimplementation.Registry
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateServiceStatus", targetNamespace = "http://ServiceImplementation.RegistryService.nure.ua/", className = "ua.nure.registryservice.serviceimplementation.UpdateServiceStatus")
    @ResponseWrapper(localName = "updateServiceStatusResponse", targetNamespace = "http://ServiceImplementation.RegistryService.nure.ua/", className = "ua.nure.registryservice.serviceimplementation.UpdateServiceStatusResponse")
    @Action(input = "http://ServiceImplementation.RegistryService.nure.ua/ServiceRegistry/updateServiceStatusRequest", output = "http://ServiceImplementation.RegistryService.nure.ua/ServiceRegistry/updateServiceStatusResponse")
    public Registry updateServiceStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Status arg1);

}
